steps:
  - name: Create a Qase test run
    uses: qase-tms/gh-actions/run-create
    id: qase-run-create
    with:
      token: ${{ secrets.QASE_TOKEN }}
      project: QE
      title: Test Run Title
      description: |
        Test Run Description
        Use multiline text and [markdown formatting](https://example.com)
      environment: my-env
      milestone: 123
      plan: 321

  - name: Run tests
    env:
      QASE_TESTOPS_PROJECT: QE
      QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TOKEN }}
      QASE_TESTOPS_RUN_ID: ${{ steps.qase-run-create.outputs.id }}
    run: |
      # Run tests here  

    
  - name: Complete a Qase test run
    uses: qase-tms/gh-actions/run-complete
    id: complete
    # use always() to run even if test step failed or job was canceled
    # but don't run if creating a test run failed before this step
    if: always() && steps.qase-run-create.result == 'success'
    with:
      token: ${{ secrets.QASE_TOKEN }}
      project: CODE
      id: ${{ steps.qase-run-create.outputs.id }}
